### PR TITLE
Iss34

### LINKED ISSUE #34: Improve testFilePathGoodCase
I'd like to change testFilePathGoodCase to make sure that the correct report is generated. If testSb2Constructor1 fails then tests like testFilePathGoodCase will also fail. The only reason to have testSb2Constructor1 is so that we can ruleout the constructor as the source of the problem if our more robust tests start to fail.

### PR DESCRIPTION
**Pull request by bclinthall**
To resolve #34 and #35.

### CODE REVIEW

**Comment by bclinthall** [comment]
Funny.  This is passing all tests and checks on my laptop, but not on Travis.  Does it fail for any of you if you download and try to build? @whereswaldon @ejcole @thehunte199

**Comment by thehunte199** [comment]
The reason travis is failing seems to be due to checkstyle errors, I'll modify things to be appropriate for checkstyle.

**Comment by thehunte199** [comment]
checkstyle now passing, testfilegoodpathcase is failing

**Comment by thehunte199** [comment]
@bclinthall @whereswaldon Added @Test modifier above testEndToEnd to see if this was the reason the test was failing, now it seems that the get Sprites script count and length tests are failing. Unsure if this is because these have been modified in some way. Let me know what you find.
Note: I created a second branch iss34-testing to test this since I was modifying more than just checkstyle errors.

**Comment by whereswaldon** [comment]
@bclinthall Are you working on this, or does someone else need to take a look?

**Comment by bclinthall** [comment]
I am not working on it yet, but plan to after I get the kids to bed.

**Comment by bclinthall** [comment]
Finally got this one to pass Travis.  File.listFiles() was giving us sb2's in a different order on our machines and on Travis's.  :-( I wish I had figured that out more quickly.

File: src/test/java/ScattTest.java [hunk 1]
```diff
@@ -123,6 +123,28 @@ public File getDirectoryFromUser() {
             fail("You need to put a file called " + testDir.getName() + "_Report.txt containing" 
                  + " the expected report contents in the test resources directory");
         }
+        if (!actual.equals(expected)) {
```
Comment (ejcole) [inline src/test/java/ScattTest.java]: It seems this would be good to include with the test utils as we might want to reuse this in other tests. As it is a nice diff feature.

File: src/test/java/ScattTest.java [hunk 2]
```diff
@@ -123,6 +123,39 @@ public File getDirectoryFromUser() {
...
```
Comment (whereswaldon) [inline src/test/java/ScattTest.java]: I'm tempted to pull in a library to do this kind of diff-ing. It's pretty complex stuff. Thoughts?

File: src/test/java/ScattTest.java (hunk 1 above)
Comment (bclinthall) [inline src/test/java/ScattTest.java]: done.
